### ISSUE TITLE
Sign-In Route

### ISSUE THREAD

**Issue by JulioLeiteSilva** [JulioLeiteSilva/filmo-backend#1]
### TODO:

- [ ] Criar rota
- [ ] Integrar banco de dados
- [ ] Desenvolver lógica de validação dos dados
- [ ] Desenvolver lógica de login
- [ ] Autenticar usuário com JWT
- [ ] Desenvolver descriptografia de senha

**Comment by JulioLeiteSilva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Desenvolver rota de login](https://trello.com/c/mazdhQwV/19-desenvolver-rota-de-login)
