### ISSUE TITLE
Sign-Up Route

### ISSUE THREAD

**Issue by JulioLeiteSilva** [JulioLeiteSilva/filmo-backend#2]
###TODO:

- [x] Criar rota
- [x] Integrar com banco de dados
- [x] Desenvolver lógica de validação dos dados
- [x] Desenvolver lógida de cadastro de usuário
- [x] Desenvolver criptografia de senha

**Comment by JulioLeiteSilva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Desenvolver rota de cadastro](https://trello.com/c/CaDOfHel/20-desenvolver-rota-de-cadastro)
